version: '3.1'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - db
    working_dir: /example
    volumes:
      - ./app:/example/app/
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: schemathesis-example
    volumes:
      - ./database:/docker-entrypoint-initdb.d
